/* sync back badge_id to the mysql file */
CREATE TABLE IF NOT EXISTS BADGES (
  `BADGE_ID` INT(11) AUTO_INCREMENT NOT NULL,
  `RFID_ID` VARCHAR(16) NOT NULL,
  `FIRST_NAME` VARCHAR(64) NULL,
  `LAST_NAME` VARCHAR(64) NULL,
  `EMAIL` VARCHAR(64) NULL,
  `PHONE` VARCHAR(45) NULL,
  `ISSUED_DATE` TIMESTAMP(6) NULL,
  PRIMARY KEY (`RFID_ID`));

CREATE TABLE IF NOT EXISTS DEVICES (
  `DEVICE_ID` INT NOT NULL,
  `DESCRIPTION` TEXT(1024) NULL,
  PRIMARY KEY (`DEVICE_ID`));

CREATE TABLE IF NOT EXISTS BADGES_HISTORY (
  `RETURN_DATE` TIMESTAMP(6) NOT NULL,
  `RFID_ID` VARCHAR(28) NOT NULL,
  `FIRST_NAME` VARCHAR(64) NULL,
  `LAST_NAME` VARCHAR(64) NULL,
  `EMAIL` VARCHAR(64) NULL,
  `PHONE` VARCHAR(45) NULL,
  `ISSUED_DATE` TIMESTAMP(6) NULL,
  PRIMARY KEY (`RETURN_DATE`, `RFID_ID`));


/* needs indexing added back */
CREATE TABLE IF NOT EXISTS ACTIVITY_LOG (
  `TIME` TIMESTAMP(6) NOT NULL,
  `BADGES_RFID_ID` VARCHAR(16) NOT NULL,
  `DEVICES_DEVICE_ID` INT NOT NULL,
  `STATUS` INT NULL,
  PRIMARY KEY (`TIME`, `BADGES_RFID_ID`, `DEVICES_DEVICE_ID`));
