
CREATE TABLE IF NOT EXISTS badges (
  BADGE_ID VARCHAR(64) NOT NULL,
  FIRST_NAME VARCHAR(64) NULL,
  LAST_NAME VARCHAR(64) NULL,
  EMAIL VARCHAR(64) NULL,
  PHONE VARCHAR(45) NULL,
  ISSUED_DATE TIMESTAMP NULL,
  PRIMARY KEY (BADGE_ID));

CREATE TABLE IF NOT EXISTS devices (
  `DEVICE_ID` VARCHAR(64) NOT NULL,
  `DESCRIPTION` TEXT(1024) NULL,
  PRIMARY KEY (`DEVICE_ID`));

CREATE TABLE IF NOT EXISTS users (
  `USERNAME` VARCHAR(128) NOT NULL,
  `PASSWORD` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`USERNAME`));

CREATE TABLE IF NOT EXISTS badges_history (
  `RETURN_DATE` TIMESTAMP NOT NULL,
  `BADGE_ID` VARCHAR(64) NOT NULL,
  `FIRST_NAME` VARCHAR(64) NULL,
  `LAST_NAME` VARCHAR(64) NULL,
  `EMAIL` VARCHAR(64) NULL,
  `PHONE` VARCHAR(45) NULL,
  `ISSUED_DATE` TIMESTAMP NULL,
  PRIMARY KEY (`RETURN_DATE`, `BADGE_ID`));

CREATE TABLE IF NOT EXISTS activity_log (
  `TIME` TIMESTAMP NOT NULL,
  `BADGE_ID` VARCHAR(64) NOT NULL,
  `DEVICE_ID` VARCHAR(64) NOT NULL,
  `STATUS` INT NULL,
  PRIMARY KEY (`TIME`, `BADGE_ID`, `DEVICE_ID`));
